apache/maven-changes-plugin

- pom.xml
> org.apache.httpcomponents upgrade

- src/site/site.xml
> live JIRA report is blank

- pom.xml
@michael-o Let's take these one at a time...
> update commons collections

- pom.xml
- src/test/java/org/apache/maven/plugins/announcement/AnnouncementMojoTest.java
> small code cleanup

- pom.xml
> update parent POM

- pom.xml
- src/main/java/org/apache/maven/plugins/changes/AbstractChangesReport.java
- src/main/java/org/apache/maven/plugins/changes/ChangesReportGenerator.java
- src/main/java/org/apache/maven/plugins/issues/AbstractIssuesReportGenerator.java
> [MCHANGES-405] update to Doxia 1.9.1 and site-tools to 1.9.2

- pom.xml
> update commons dependencies

- src/main/java/org/apache/maven/plugins/changes/IssueAdapter.java
- src/test/java/org/apache/maven/plugins/changes/IssueAdapterTest.java
> [MCHANGES-419] Make IssueAdapter#getReleases return releases in a sensible order

- pom.xml
- src/main/java/org/apache/maven/plugins/github/GitHubDownloader.java
- src/test/java/org/apache/maven/plugins/github/GitHubDownloaderTestCase.java
Following this checklist to help us incorporate your
contribution quickly and easily:
for the change (usually before you start working on it).  Trivial changes like typos do not
require a JIRA issue. Your pull request should address just this issue, without
pulling in other changes.
where you replace `MCHANGES-XXX` and `SUMMARY` with the appropriate JIRA issue.
Best practice is to use the JIRA issue title in both the pull request title and in the first line of the commit message.
If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.
To make clear that you license your contribution under
the [Apache License Version 2.0, January …
> [MCHANGES-431] Replace GitHub client with recommended client from docs

- src/main/java/org/apache/maven/plugins/changes/ChangesReport.java
- src/main/java/org/apache/maven/plugins/changes/schema/DefaultChangesSchemaValidator.java
- src/main/java/org/apache/maven/plugins/github/GitHubReport.java
- src/main/java/org/apache/maven/plugins/jira/JiraReport.java
- src/main/java/org/apache/maven/plugins/trac/TracReport.java
https://issues.apache.org/jira/browse/MCHANGES-437
> [MCHANGES-437] Drop usage of deprecated items

- src/site/site.xml
- src/site/xdoc/download.xml.vm
https://issues.apache.org/jira/browse/MCHANGES-440
> [MCHANGES-440] Refresh download page

- src/main/java/org/apache/maven/plugins/changes/ChangesCheckMojo.java
- src/main/java/org/apache/maven/plugins/changes/ChangesReport.java
- src/main/java/org/apache/maven/plugins/changes/ChangesReportRenderer.java
- src/main/java/org/apache/maven/plugins/changes/ReleaseUtils.java
- src/main/java/org/apache/maven/plugins/changes/announcement/AnnouncementMojo.java
- src/main/java/org/apache/maven/plugins/changes/github/GitHubReport.java
- src/main/java/org/apache/maven/plugins/changes/issues/AbstractIssuesReportRenderer.java
- src/main/java/org/apache/maven/plugins/changes/issues/IssuesReportHelper.java
- src/main/java/org/apache/maven/plugins/changes/issues/IssuesReportRenderer.java
- src/main/java/org/apache/maven/plugins/changes/jira/JiraReport.java
- src/main/java/org/apache/maven/plugins/changes/trac/TracReport.java
- src/test/java/org/apache/maven/plugins/changes/ReleaseUtilsTest.java
- rename Generator to Renderer
- use methods from AbstractMavenReportRenderer
- remove not used or not needed methods
> [MCHANGES-427] Use AbstractMavenReportRenderer and renderer refactor

- src/it/report-jira/setup.groovy
- src/main/java/org/apache/maven/plugins/changes/jira/RestJiraDownloader.java
https://issues.apache.org/jira/browse/MCHANGES-309
> [MCHANGES-309] Check for NullNodes in RestJiraDownloader

- src/main/java/org/apache/maven/plugins/changes/announcement/AnnouncementMojo.java
- src/main/java/org/apache/maven/plugins/changes/trac/TracChangesReport.java
- src/site/apt/index.apt.vm
https://issues.apache.org/jira/browse/MCHANGES-454
> [MCHANGES-454] Deprecate Trac integration

- src/test/java/org/apache/maven/plugins/changes/ChangesXMLTest.java
- src/test/java/org/apache/maven/plugins/changes/jira/JqlQueryBuilderTestCase.java
General principle of TDD: passing tests generate no output
> Silence logs in test

- src/it/report-changes-generation/src/changes/changes.xml
- src/it/report-changes-generation/verify.groovy
- src/main/java/org/apache/maven/plugins/changes/ChangesReportRenderer.java
- src/main/mdo/changes.mdo
https://issues.apache.org/jira/browse/MCHANGES-456
> [MCHANGES-456] Make dev attribute optional in changes.xml

- src/it/announce-generate-inconsistent-issue-management/src/changes/changes.xml
- src/it/announce-generate-no-issue-management/src/changes/changes.xml
- src/it/announce-generate-no-url/src/changes/changes.xml
- src/it/announce-generate/src/changes/changes.xml
- src/it/announcement-generate-custom-template/src/changes/changes.xml
- src/it/email-sender/src/changes/changes.xml
- src/it/report-aggregated-changes-generation/module1/src/changes/changes.xml
- src/it/report-aggregated-changes-generation/module3/src/changes/changes.xml
- src/it/report-aggregated-changes-generation/src/changes/changes.xml
- src/it/report-changes-generation/src/changes/changes.xml
- src/it/report-changes-interpolation/src/changes/changes.xml
- src/main/mdo/changes.mdo
- src/site/apt/index.apt.vm
- src/site/changes/sample-changes.xml
- src/test/unit/announce-changes.xml
- src/test/unit/changes.xml
https://issues.apache.org/jira/browse/MCHANGES-457
> [MCHANGES-457] Rename attribute fixedIssues to fixed-issues

- src/main/java/org/apache/maven/plugins/changes/announcement/AnnouncementMojo.java
- src/main/java/org/apache/maven/plugins/changes/jira/JIRAIssueManagementSystem.java
- src/test/java/org/apache/maven/plugins/changes/IssueAdapterTest.java
https://issues.apache.org/jira/browse/MCHANGES-460
> [MCHANGES-460] JIRA - Add Dependency upgrade, Task, Wish to default type mapping

- pom.xml
https://issues.apache.org/jira/browse/MCHANGES-461
> [MCHANGES-461] Use new report names in project build

- src/site/apt/examples/alternate-changes-xml-location.apt.vm
> No longer care when this feature was introduced

- pom.xml
- src/site/site.xml
Following this checklist to help us incorporate your
contribution quickly and easily:
for the change (usually before you start working on it).  Trivial changes like typos do not
require a JIRA issue. Your pull request should address just this issue, without
pulling in other changes.
where you replace `MCHANGES-XXX` and `SUMMARY` with the appropriate JIRA issue.
Best practice is to use the JIRA issue title in both the pull request title and in the first line of the commit message.
If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.
To make clear that you license your contribution under
the [Apache License Version 2.0, January …
> Update site descriptor
